export enum ErrorType {
  JSONDataExcpected = 'data-not-json-object',
  MessageTypeExpected = 'message-type-not-defined',
  MessageTypeAllowed = 'message-type-not-allowed',
  JoinedAlready = 'joined-already',
  UsernameRequired = 'username-required',
  UsernameString = 'username-not-string',
  UsernameInvalid = 'username-invalid',
  UsernameInUse = 'username-in-use',
  NotJoined = 'not-joined',
  UsernameOrPropertiesUpdate = 'username-or-properties-update-allowed',

  // JoinedAlready = 'joined-already',
  // MessageToSelf = 'cannot-send-message-to-yourself',
  // RecipientNotConnected = 'recipient-not-connected',
  // ExpectedPlayersNotSpecified = 'expected-players-not-specified',
  // ExpectedPlayersNotConnected = 'expected-players-not-connected',
  // SomeExpectedPlayersNotConnected = 'some-expected-players-not-connected',
  // GameNotFound = 'game-not-found',
  // ClientNotInGame = 'not-in-game',
  // RestarErrorRoomNotFilled = 'not-all-players-in-game-to-request-restart',
  // GameNotStarted = 'game-not-started-to-request-restart',
  // RestartNotRequested = 'restart-not-requested',
  // CannotUpdateWhenRestartRequested = 'cannot-update-game-when-restart-requested',
  // CannotEndWhenRestartRequested = 'cannot-end-game-when-restart-requested',
  // WaitForPlayersToJoin = 'wait-for-players-to-join',
  // GameActionForbidden = 'game-action-forbidden',
  // GameEntranceForbidden = 'game-entrance-forbidden',
}
