export enum ErrorType {
  UsernameRequired = 'username-required',
  // UsernameInvalid = 'username-invalid',
  // UsernameInUse = 'username-in-use',
  // NotJoined = 'not-joined',
  // JoinedAlready = 'joined-already',
  // MessageToSelf = 'cannot-send-message-to-yourself',
  // RecipientNotConnected = 'recipient-not-connected',
  // ExpectedPlayersNotSpecified = 'expected-players-not-specified',
  // ExpectedPlayersNotConnected = 'expected-players-not-connected',
  // SomeExpectedPlayersNotConnected = 'some-expected-players-not-connected',
  // GameNotFound = 'game-not-found',
  // ClientNotInGame = 'not-in-game',
  // RestarErrorRoomNotFilled = 'not-all-players-in-game-to-request-restart',
  // GameNotStarted = 'game-not-started-to-request-restart',
  // RestartNotRequested = 'restart-not-requested',
  // CannotUpdateWhenRestartRequested = 'cannot-update-game-when-restart-requested',
  // CannotEndWhenRestartRequested = 'cannot-end-game-when-restart-requested',
  // WaitForPlayersToJoin = 'wait-for-players-to-join',
  // GameActionForbidden = 'game-action-forbidden',
  // GameEntranceForbidden = 'game-entrance-forbidden',
}
